---
dist: trusty
language: python
python: "2.7"

sudo: true

env:
  - lxd_container_alias: ubuntu/trusty/amd64
  - lxd_container_alias: ubuntu/xenial/amd64
  - lxd_container_alias: centos/7/amd64

install:
  # Installing latest ansible
  - sudo -H pip install ansible
  # Cloning testing template
  - sudo mkdir /etc/ansible
  - sudo chown -R "${USER}:" /etc/ansible
  - git clone https://github.com/Nani-o/ansible-template-role-test /etc/ansible
  # Executing setup
  - ansible-playbook /etc/ansible/setup.yml
  - sudo -E su $USER -c "ansible-playbook /etc/ansible/test.yml"

script:
  # Run tests.
  - ansible --version
